import { typography } from "./typography";

export const fontStyles = {
  // Display
  display1: {
    fontFamily: typography.fontFamily.pre,
    fontWeight: typography.fontWeight[600],
    fontSize: typography.fontSize[55],
    lineHeight: typography.lineHeight[27],
    letterSpacing: typography.letterSpacing[400],
  },
  display2: {
    fontFamily: typography.fontFamily.pre,
    fontWeight: typography.fontWeight[600],
    fontSize: typography.fontSize[40],
    lineHeight: typography.lineHeight[27],
    letterSpacing: typography.letterSpacing[400],
  },
  display3: {
    fontFamily: typography.fontFamily.pre,
    fontWeight: typography.fontWeight[700],
    fontSize: typography.fontSize[36],
    lineHeight: typography.lineHeight[27],
    letterSpacing: typography.letterSpacing["000"],
  },
  display4: {
    fontFamily: typography.fontFamily.pre,
    fontWeight: typography.fontWeight[600],
    fontSize: typography.fontSize[36],
    lineHeight: typography.lineHeight[27],
    letterSpacing: typography.letterSpacing[400],
  },
  display5: {
    fontFamily: typography.fontFamily.SB,
    fontWeight: typography.fontWeight[700],
    fontSize: typography.fontSize[35],
    lineHeight: typography.lineHeight[27],
    letterSpacing: typography.letterSpacing[300],
  },
  display6: {
    fontFamily: typography.fontFamily.pre,
    fontWeight: typography.fontWeight[600],
    fontSize: typography.fontSize[32],
    lineHeight: typography.lineHeight[27],
    letterSpacing: typography.letterSpacing[400],
  },
  display7: {
    fontFamily: typography.fontFamily.pre,
    fontWeight: typography.fontWeight[600],
    fontSize: typography.fontSize[30],
    lineHeight: typography.lineHeight[27],
    letterSpacing: typography.letterSpacing[300],
  },

  // Heading
  heading1: {
    fontFamily: typography.fontFamily.pre,
    fontWeight: typography.fontWeight[600],
    fontSize: typography.fontSize[28],
    lineHeight: typography.lineHeight[27],
    letterSpacing: typography.letterSpacing[200],
  },
  heading2: {
    fontFamily: typography.fontFamily.pre,
    fontWeight: typography.fontWeight[600],
    fontSize: typography.fontSize[22],
    lineHeight: typography.lineHeight[27],
    letterSpacing: typography.letterSpacing[200],
  },
  heading3: {
    fontFamily: typography.fontFamily.pre,
    fontWeight: typography.fontWeight[700],
    fontSize: typography.fontSize[21],
    lineHeight: typography.lineHeight[27],
    letterSpacing: typography.letterSpacing[200],
  },
  heading4: {
    fontFamily: typography.fontFamily.pre,
    fontWeight: typography.fontWeight[600],
    fontSize: typography.fontSize[20],
    lineHeight: typography.lineHeight[27],
    letterSpacing: typography.letterSpacing[200],
  },

  // Subtitle
  subtitle1: {
    fontFamily: typography.fontFamily.pre,
    fontWeight: typography.fontWeight[400],
    fontSize: typography.fontSize[20],
    lineHeight: typography.lineHeight[27],
    letterSpacing: typography.letterSpacing["000"],
  },
  subtitle2: {
    fontFamily: typography.fontFamily.pre,
    fontWeight: typography.fontWeight[700],
    fontSize: typography.fontSize[18],
    lineHeight: typography.lineHeight[27],
    letterSpacing: typography.letterSpacing[200],
  },
  subtitle3: {
    fontFamily: typography.fontFamily.jet,
    fontWeight: typography.fontWeight[400],
    fontSize: typography.fontSize[20],
    lineHeight: typography.lineHeight[27],
    letterSpacing: typography.letterSpacing["000"],
  },
  subtitle4: {
    fontFamily: typography.fontFamily.jet,
    fontWeight: typography.fontWeight[700],
    fontSize: typography.fontSize[18],
    lineHeight: typography.lineHeight[27],
    letterSpacing: typography.letterSpacing[200],
  },

  // Body
  body1: {
    fontFamily: typography.fontFamily.pre,
    fontWeight: typography.fontWeight[500],
    fontSize: typography.fontSize[18],
    lineHeight: typography.lineHeight[31],
    letterSpacing: typography.letterSpacing["000"],
  },
  body2: {
    fontFamily: typography.fontFamily.pre,
    fontWeight: typography.fontWeight[600],
    fontSize: typography.fontSize[18],
    lineHeight: typography.lineHeight[31],
    letterSpacing: typography.letterSpacing["000"],
  },
  body3: {
    fontFamily: typography.fontFamily.pre,
    fontWeight: typography.fontWeight[400],
    fontSize: typography.fontSize[18],
    lineHeight: typography.lineHeight[29],
    letterSpacing: typography.letterSpacing["000"],
  },
  body4: {
    fontFamily: typography.fontFamily.pre,
    fontWeight: typography.fontWeight[800],
    fontSize: typography.fontSize[16],
    lineHeight: typography.lineHeight[27],
    letterSpacing: typography.letterSpacing[300],
  },
  body5: {
    fontFamily: typography.fontFamily.pre,
    fontWeight: typography.fontWeight[500],
    fontSize: typography.fontSize[16],
    lineHeight: typography.lineHeight[27],
    letterSpacing: typography.letterSpacing["000"],
  },
  body6: {
    fontFamily: typography.fontFamily.pre,
    fontWeight: typography.fontWeight[600],
    fontSize: typography.fontSize[16],
    lineHeight: typography.lineHeight[27],
    letterSpacing: typography.letterSpacing["000"],
  },
  body7: {
    fontFamily: typography.fontFamily.pre,
    fontWeight: typography.fontWeight[700],
    fontSize: typography.fontSize[16],
    lineHeight: typography.lineHeight[27],
    letterSpacing: typography.letterSpacing["000"],
  },
  body8: {
    fontFamily: typography.fontFamily.jet,
    fontWeight: typography.fontWeight[500],
    fontSize: typography.fontSize[17],
    lineHeight: typography.lineHeight[27],
    letterSpacing: typography.letterSpacing["000"],
  },
  body9: {
    fontFamily: typography.fontFamily.jet,
    fontWeight: typography.fontWeight[700],
    fontSize: typography.fontSize[16],
    lineHeight: typography.lineHeight[26],
    letterSpacing: typography.letterSpacing["000"],
  },
  body10: {
    fontFamily: typography.fontFamily.jet,
    fontWeight: typography.fontWeight[600],
    fontSize: typography.fontSize[16],
    lineHeight: typography.lineHeight[27],
    letterSpacing: typography.letterSpacing[200],
  },
  body11: {
    fontFamily: typography.fontFamily.jet,
    fontWeight: typography.fontWeight[400],
    fontSize: typography.fontSize[16],
    lineHeight: typography.lineHeight[27],
    letterSpacing: typography.letterSpacing["000"],
  },
  body12: {
    fontFamily: typography.fontFamily.jet,
    fontWeight: typography.fontWeight[700],
    fontSize: typography.fontSize[14],
    lineHeight: typography.lineHeight[27],
    letterSpacing: typography.letterSpacing["000"],
  },
  body13: {
    fontFamily: typography.fontFamily.jet,
    fontWeight: typography.fontWeight[400],
    fontSize: typography.fontSize[14],
    lineHeight: typography.lineHeight[24],
    letterSpacing: typography.letterSpacing["000"],
  },
  body14: {
    fontFamily: typography.fontFamily.D2,
    fontWeight: typography.fontWeight[400],
    fontSize: typography.fontSize[16],
    lineHeight: typography.lineHeight[27],
    letterSpacing: typography.letterSpacing[300],
  },
  // Caption
  caption1: {
    fontFamily: typography.fontFamily.pre,
    fontWeight: typography.fontWeight[500],
    fontSize: typography.fontSize[14],
    lineHeight: typography.lineHeight[27],
    letterSpacing: typography.letterSpacing["000"],
  },
  caption2: {
    fontFamily: typography.fontFamily.pre,
    fontWeight: typography.fontWeight[500],
    fontSize: typography.fontSize[14],
    lineHeight: typography.lineHeight[27],
    letterSpacing: typography.letterSpacing[500],
  },
  caption3: {
    fontFamily: typography.fontFamily.pre,
    fontWeight: typography.fontWeight[600],
    fontSize: typography.fontSize[14],
    lineHeight: typography.lineHeight[27],
    letterSpacing: typography.letterSpacing["000"],
  },
  caption4: {
    fontFamily: typography.fontFamily.pre,
    fontWeight: typography.fontWeight[500],
    fontSize: typography.fontSize[14],
    lineHeight: typography.lineHeight[27],
    letterSpacing: typography.letterSpacing[100],
  },
  caption5: {
    fontFamily: typography.fontFamily.pre,
    fontWeight: typography.fontWeight[700],
    fontSize: typography.fontSize[13],
    lineHeight: typography.lineHeight[27],
    letterSpacing: typography.letterSpacing[100],
  },
  caption6: {
    fontFamily: typography.fontFamily.jet,
    fontWeight: typography.fontWeight[500],
    fontSize: typography.fontSize[12],
    lineHeight: typography.lineHeight[27],
    letterSpacing: typography.letterSpacing["000"],
  },
  caption7: {
    fontFamily: typography.fontFamily.jet,
    fontWeight: typography.fontWeight[500],
    fontSize: typography.fontSize[10],
    lineHeight: typography.lineHeight[27],
    letterSpacing: typography.letterSpacing["000"],
  },
} as const;

export type FontStylesType = typeof fontStyles;
export type FontStyleVariant = keyof typeof fontStyles;
