import "../styles/reset.css";
import "../styles/theme.css";
import "../styles/global.css";

import type { Metadata } from "next";
import { JetBrains_Mono } from "next/font/google";
import localFont from "next/font/local";

const pretendard = localFont({
  src: "../../public/fonts/subset-PretendardVariable.woff2",
  variable: "--font-pretendard",
  display: "swap",
});

const jetbrainsMono = JetBrains_Mono({
  subsets: ["latin"],
  variable: "--font-jetbrains-mono",
  display: "swap",
});

const D2 = localFont({
  src: "../../public/fonts/D2Coding.woff2",
  variable: "--font-D2",
  display: "swap",
});

const SB = localFont({
  src: "../../public/fonts/SB-Aggro.woff2",
  variable: "--font-SB",
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="ko"
      className={`${pretendard.variable} ${jetbrainsMono.variable} ${D2.variable} ${SB.variable}`}
    >
      <body>{children}</body>
    </html>
  );
}
